/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.hellochengkai.github;

public class App {
    public static void main(String[] args) {
        new SchedulerTest().run();
    }
}
