/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.hellochengkai.github;
import com.hellochengkai.github.test.FlowableTest;

public class App {
    public static void main(String[] args) {
        new FlowableTest().run();
        try {
            Thread.sleep(1000 * 60 * 2);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

    }
}
