/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.hellochengkai.github;

import com.hellochengkai.github.test.ColdAndHot.Cold2Hot.ConnectableObservableTest;
import com.hellochengkai.github.test.ColdAndHot.Cold2Hot.SubjectTest;
import com.hellochengkai.github.test.ColdAndHot.Hot2Cold.RefCountTest;

public class App {
    public static void main(String[] args) {
//        new ObservableTest().apply(null);
//        new FlowableTest().apply(null);
//        new SingleTest().apply(null);
//        new CompletableTest().run();
//        new MaybeTest().run();
        new RefCountTest().run();
    }
}
